### ISSUE TITLE
prctica 1

### ISSUE THREAD

**Issue by franciscop1s3** [UG-OS2016/Practicas#1]
compañeros y profesor la practica que tenemos ba a ser para el lunes regresando de vacaciones?(es que no tiene fecha?, y si se ba a escribir como fue que le hicimos para instalar oracle java o solo limitarnos  hacer lo que dice en la practica?

**Comment by JuanCrg90** [comment]
Prácticamente tu reporte debe mostrar paso a paso la instalación de Oracle Java en tu sistema

https://github.com/UG-OS2016/Practicas/tree/master/practica_1

SI TIENE FECHA DE ENTREGA. Por favor revisa con atención
