### ISSUE TITLE
Duda

### ISSUE THREAD

**Issue by Pablo9092** [UG-OS2016/Practicas#2]
Hola Profesor ya verfique los permisos de la carpeta, el problema es que no tengo el archivo de configure y no se que hacer para saber cual es el archivo equivalente a configure o si tengo que agregarlo

**Comment by JuanCrg90** [comment]
por favor haz un `ls -l` a esa carpeta y sube una toma de pantalla

Actualiza el asunto del issue y ponte una fotografía en al cuenta, creí solicitarlo al inicio del curso.

**Comment by Pablo9092** [comment]
![permisos](https://cloud.githubusercontent.com/assets/17110552/14151099/8a68e940-f669-11e5-93e8-8053213f7a1e.png)

**Comment by JuanCrg90** [comment]
en que fuente te estas basando?

**Comment by Pablo9092** [comment]
He visto dos tutoriales  y varias paginas en internet y me dicen que es asi, y en algunas me dicen que busque el un documento que dice readme, que por que luego ahi viene maneras particulares de como instalar el programa, y en esa viene ese documento pero no dice nada sobre la instalacion  o talvez no se cual es la parte donde vienen y eso ando buscando Profe la manera de instalarlo desde la pagina de Oracle.

**Comment by Pablo9092** [comment]
Este enlace  es de la ayuda del programa viene en el archivo README 
http://www.oracle.com/technetwork/java/javase/jdk-8-readme-2095712.html
Y los siguientes son los que he visto:
http://blog.desdelinux.net/tutorial-instalar-paquetes-tar-gz-y-tar-bz2/
http://rootear.com/ubuntu-linux/paquetes-tar-gz-linux
http://www.taringa.net/post/linux/9928134/Como-instalar-archivos-tar-gz-o-gz-en-ubuntu.html

**Comment by Pablo9092** [comment]
Profesor tengo un problema, lo que pasa es que quiero intentar Fedora pero no se como, vi algunos tutoriales solo que al intentar hacer la memoria buteable me marca un error y no se que hacer me manda una pantalla negra, y dice algo de que tengo que salir del shell para poder llevar acaba la instalacion,  no se si es normal que salga esa pantalla negra diciendo que hay un error que salga del shell?

**Comment by JuanCrg90** [comment]
Prueba con un CD, por favor usa asuntos que digan algo. Duda no refleja nada además de que ya estás tratando otro tópico.
