### ISSUE TITLE
Dudas sobre el proceso

### ISSUE THREAD

**Issue by ericknegreter** [UG-OS2016/Practicas#4]
Buenas noches profesor. Vera mi duda es sobre como debemos proceder a la hora de instalar los Apache, MySql, etc. Podemos utilizar por ejemplo sudo apt-get update o sudo apt-get install o debemos hacerlo totalmente a pie como en la practica pasada. De ante mano gracias.

**Comment by JuanCrg90** [comment]
Usando sudo apt-get install, pero debe ser cada paquete de manera individual

_Juan Carlos Ruiz GonzálezSitio Web http://juancrg90.me/ | *_Twitter
https://twitter.com/juancrg90 | Linkedin
https://www.linkedin.com/in/juancrg90 | Github
http://github.com/JuanCrg90*

2016-05-16 22:58 GMT-05:00 Erick Negrete Ramos notifications@github.com:

**Comment by ericknegreter** [comment]
ok profesor muchisimas gracias.
