### ISSUE TITLE
Duda sobre práctica 3

### ISSUE THREAD

**Issue by javbar** [UG-OS2016/Practicas#6]
En el problema 2, lo que quiere es un reloj en la terminal? o qué es lo que se pide?
Y toca hacer reporte de esta práctica o sólo toca enviar los scripts?

**Comment by JuanCrg90** [comment]
Un reloj en terminal, hay un comando que muestra la hora. Buscalo. No no se
ocupa reporte

**Comment by javbar** [comment]
Ok, gracias por la respuesta.
